-- MySQL Script generated by MySQL Workbench
-- 10/30/17 19:35:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EnderecoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EnderecoUsuario` (
  `idEnderecoUsuario` INT NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(90) NOT NULL,
  `bairro` VARCHAR(90) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idEnderecoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `idLogin` INT NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `tipo` CHAR(1) NOT NULL,
  PRIMARY KEY (`idLogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `EnderecoUsuario_idEnderecoUsuario` INT NOT NULL,
  `Login_idLogin` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `EnderecoUsuario_idEnderecoUsuario`, `Login_idLogin`),
  INDEX `fk_Usuario_EnderecoUsuario_idx` (`EnderecoUsuario_idEnderecoUsuario` ASC),
  INDEX `fk_Usuario_Login1_idx` (`Login_idLogin` ASC),
  CONSTRAINT `fk_Usuario_EnderecoUsuario`
    FOREIGN KEY (`EnderecoUsuario_idEnderecoUsuario`)
    REFERENCES `mydb`.`EnderecoUsuario` (`idEnderecoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Login1`
    FOREIGN KEY (`Login_idLogin`)
    REFERENCES `mydb`.`Login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Modalidade` (
  `idModalidade` INT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idModalidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `idEstado` INT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Livros` (
  `idLivros` INT NOT NULL,
  `qtdPaginas` CHAR(5) NOT NULL,
  `edicao` VARCHAR(45) NULL,
  PRIMARY KEY (`idLivros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roupas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roupas` (
  `idRoupas` INT NOT NULL,
  `tamanho` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idRoupas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brinquedos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brinquedos` (
  `idBrinquedos` INT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBrinquedos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Modalidade_idModalidade` INT NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  `Livros_idLivros` INT NULL,
  `Roupas_idRoupas` INT NULL,
  `Brinquedos_idBrinquedos` INT NULL,
  PRIMARY KEY (`idProduto`, `Usuario_idUsuario`),
  INDEX `fk_Produto_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Produto_Modalidade1_idx` (`Modalidade_idModalidade` ASC),
  INDEX `fk_Produto_Estado1_idx` (`Estado_idEstado` ASC),
  INDEX `fk_Produto_Livros1_idx` (`Livros_idLivros` ASC),
  INDEX `fk_Produto_Roupas1_idx` (`Roupas_idRoupas` ASC),
  INDEX `fk_Produto_Brinquedos1_idx` (`Brinquedos_idBrinquedos` ASC),
  CONSTRAINT `fk_Produto_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Modalidade1`
    FOREIGN KEY (`Modalidade_idModalidade`)
    REFERENCES `mydb`.`Modalidade` (`idModalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `mydb`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Livros1`
    FOREIGN KEY (`Livros_idLivros`)
    REFERENCES `mydb`.`Livros` (`idLivros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Roupas1`
    FOREIGN KEY (`Roupas_idRoupas`)
    REFERENCES `mydb`.`Roupas` (`idRoupas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Brinquedos1`
    FOREIGN KEY (`Brinquedos_idBrinquedos`)
    REFERENCES `mydb`.`Brinquedos` (`idBrinquedos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
