-- MySQL Script generated by MySQL Workbench
-- 11/01/17 19:49:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `antallagi` DEFAULT CHARACTER SET utf8 ;
USE `antallagi` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EnderecoUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EnderecoUsuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EnderecoUsuario` (
  `idEnderecoUsuario` INT NOT NULL AUTO_INCREMENT,
  `complemento` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(90) NOT NULL,
  `bairro` VARCHAR(90) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(80) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEnderecoUsuario`),
  INDEX `fk_EnderecoUsuario_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_EnderecoUsuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Login` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(120) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `tipo` CHAR(1) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idLogin`),
  INDEX `fk_Login_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Login_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modalidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Modalidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Modalidade` (
  `idModalidade` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idModalidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Livros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Livros` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Livros` (
  `idLivros` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `qtdPaginas` CHAR(5) NOT NULL,
  `edicao` VARCHAR(45) NULL,
  PRIMARY KEY (`idLivros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roupas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Roupas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Roupas` (
  `idRoupas` INT NOT NULL AUTO_INCREMENT,
  `tamanho` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idRoupas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brinquedos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Brinquedos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Brinquedos` (
  `idBrinquedos` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBrinquedos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `valor` DOUBLE(9,2) NULL,
  `qtde` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Modalidade_idModalidade` INT NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  `Livros_idLivros` INT NULL,
  `Roupas_idRoupas` INT NULL,
  `Brinquedos_idBrinquedos` INT NULL,
  PRIMARY KEY (`idProduto`, `Usuario_idUsuario`),
  INDEX `fk_Produto_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Produto_Modalidade1_idx` (`Modalidade_idModalidade` ASC),
  INDEX `fk_Produto_Estado1_idx` (`Estado_idEstado` ASC),
  INDEX `fk_Produto_Livros1_idx` (`Livros_idLivros` ASC),
  INDEX `fk_Produto_Roupas1_idx` (`Roupas_idRoupas` ASC),
  INDEX `fk_Produto_Brinquedos1_idx` (`Brinquedos_idBrinquedos` ASC),
  CONSTRAINT `fk_Produto_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Modalidade1`
    FOREIGN KEY (`Modalidade_idModalidade`)
    REFERENCES `mydb`.`Modalidade` (`idModalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `mydb`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Livros1`
    FOREIGN KEY (`Livros_idLivros`)
    REFERENCES `mydb`.`Livros` (`idLivros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Roupas1`
    FOREIGN KEY (`Roupas_idRoupas`)
    REFERENCES `mydb`.`Roupas` (`idRoupas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Brinquedos1`
    FOREIGN KEY (`Brinquedos_idBrinquedos`)
    REFERENCES `mydb`.`Brinquedos` (`idBrinquedos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ListaClassificacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ListaClassificacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ListaClassificacao` (
  `idListaClassificacao` INT NOT NULL AUTO_INCREMENT,
  `classificacao` CHAR(1) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idListaClassificacao`),
  INDEX `fk_ListaClassificacao_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_ListaClassificacao_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Historico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Historico` (
  `idHistorico` INT NOT NULL AUTO_INCREMENT,
  `idProduto` INT NOT NULL,
  `Vendedor` INT NOT NULL,
  `Comprador` INT NOT NULL,
  `idListaClassificacao` INT NULL,
  `Historicocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idHistorico`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-----------------------------------------------------
--POPULAçÃO
-----------------------------------------------------
Insert into Usuario VALUES(null,"Natan","01/01/1899","M","33333433");
Insert into Usuario VALUES(null,"Jorge","16/04/2015","M","33334333");
Insert into Usuario VALUES(null,"Lucas","28/12/2000","M","33343333");
Insert into Usuario VALUES(null,"Usuario","28/12/2005","M","33344444");

Insert into Login VALUES(null,"natan@maiscedo.com.br","1234","1",1);
Insert into Login VALUES(null,"jorge@hotmail.com.br","1234","1",2);
Insert into Login VALUES(null,"lucas@hotmail.com.br","1234","1",3);
Insert into Login VALUES(null,"usuario@email.com","a7d80ffeefa212b7c5c55700e4f7193e","1",4);

Insert into EnderecoUsuario(null,"79","1110","Rua Virgilio da mata","Seis Tubarao","Belo Horizonte","Minas Gerais",1);
Insert into EnderecoUsuario(null,"15","754","Rua Robertim da milharal","Depoisllagi","Belo Horizonte","Minas Gerais",2);
Insert into EnderecoUsuario(null,"31","98544","Rua Conceissao Mato Fora","Yajui","Belo Horizonte","Minas Gerais",3);



Insert into Modalidade VALUES(null, "Venda");
Insert into Modalidade VALUES(null, "Doação");
Insert into Modalidade VALUES(null, "Troca");

Insert into Estado VALUES(null, "Usado");
Insert into Estado VALUES(null, "Novo");

Insert into Roupas VALUES(null,"P","Blusinha rosa do Natan");
Insert into Roupas VALUES(null,"M","Vestidinho rosa do Natan");
Insert into Roupas VALUES(null,"G","Saia beje do Natan");

Insert into Brinquedos VALUES(null, "Barbie do Natan");
Insert into Brinquedos VALUES(null, "Max Steel do Natan");
Insert into Brinquedos VALUES(null, "Pollie do Natan");

Insert into Livros VALUES ( null,"456", "A revolta de Karl Marx",null);
Insert into Livros VALUES ( null,"566", "Natan no País das Maravilhas",null);
Insert into Livros VALUES ( null,"456", "Batman e a Guerra dos Ciriguejo",null);

Insert into Produto VALUES(null,null,"1",1,2,1,null,1,null);
Insert into Produto VALUES(null,null,"2",1,3,2,null,2,null);
Insert into Produto VALUES(null,null,"3",1,1,2,null,3,null);

Insert into Produto VALUES(null,null,"1",2,1,2,1,null,null);
Insert into Produto VALUES(null,null,"1",2,2,1,2,null,null);
Insert into Produto VALUES(null,null,"1",2,3,1,3,null,null);

Insert into Produto VALUES(null,null,"1",3,3,1,null,null,3);
Insert into Produto VALUES(null,null,"1",3,2,2,null,null,2);
Insert into Produto VALUES(null,null,"1",3,1,1,null,null,1);








